/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import conexaobd.ModuloConexao;
/**
 *
 * @author Alunos
 */
public class DelayScreen extends javax.swing.JFrame {
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form DelayScreen
     */
    public DelayScreen() {
        initComponents();
        conexao = ModuloConexao.conector();
    }
    public String station;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtReasonDelay = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputReasonDelay = new javax.swing.JTextArea();
        txtTypeDelay = new javax.swing.JLabel();
        inputType1 = new javax.swing.JRadioButton();
        inputType2 = new javax.swing.JRadioButton();
        inputType3 = new javax.swing.JRadioButton();
        inputType4 = new javax.swing.JRadioButton();
        buttonSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atraso");

        txtReasonDelay.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtReasonDelay.setText("MOTIVO DO ATRASO");

        inputReasonDelay.setColumns(20);
        inputReasonDelay.setRows(5);
        inputReasonDelay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputReasonDelayKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(inputReasonDelay);

        txtTypeDelay.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtTypeDelay.setText("TIPO DO ATRASO");

        buttonGroup1.add(inputType1);
        inputType1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        inputType1.setText("M1");
        inputType1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputType1KeyPressed(evt);
            }
        });

        buttonGroup1.add(inputType2);
        inputType2.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        inputType2.setText("M2");
        inputType2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputType2KeyPressed(evt);
            }
        });

        buttonGroup1.add(inputType3);
        inputType3.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        inputType3.setText("M3");
        inputType3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputType3KeyReleased(evt);
            }
        });

        buttonGroup1.add(inputType4);
        inputType4.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        inputType4.setText("M4");
        inputType4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputType4KeyPressed(evt);
            }
        });

        buttonSave.setText("SALVAR");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });
        buttonSave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buttonSaveKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSave)
                    .addComponent(txtTypeDelay)
                    .addComponent(txtReasonDelay)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputType1)
                            .addComponent(inputType2))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputType4)
                            .addComponent(inputType3))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtReasonDelay)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTypeDelay)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputType1)
                    .addComponent(inputType3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputType2)
                    .addComponent(inputType4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonSave)
                .addGap(14, 14, 14))
        );

        setSize(new java.awt.Dimension(581, 429));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void addTemporary(String reasonDelay, String typeDelay){
        String sql = "insert into auxDelay(reasonDelay,typeDelay) values(?,?)";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1,reasonDelay);
            pst.setString(2,typeDelay);
            pst.executeUpdate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void beforeAdd(){
        boolean emptyInput=false;
        if(inputReasonDelay.getText().equals("")){
            emptyInput=true;
        }
        String reasonDelay = inputReasonDelay.getText();
        String typeDelay = null;
        if(inputType1.isSelected()&&emptyInput==false){
            typeDelay = "M1";
            this.dispose();
        }
        else if(inputType2.isSelected()&&emptyInput==false){
            typeDelay = "M2";
            this.dispose();
        }
        else if(inputType3.isSelected()&&emptyInput==false){
            typeDelay = "M3";
            this.dispose();
        }
        else if(inputType4.isSelected()&&emptyInput==false){
            typeDelay = "M4";
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "PREENCHA O MOTIVO DO ATRASO E ESCOLHA O TIPO TAMBÉM");
        }
        if(typeDelay!=null){
            addTemporary(reasonDelay, typeDelay);
        }
    }
    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        beforeAdd();
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void inputReasonDelayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputReasonDelayKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            inputType1.requestFocus();
        }
    }//GEN-LAST:event_inputReasonDelayKeyPressed

    private void inputType1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputType1KeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            beforeAdd();
        }
    }//GEN-LAST:event_inputType1KeyPressed

    private void inputType2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputType2KeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            beforeAdd();
        }
    }//GEN-LAST:event_inputType2KeyPressed

    private void inputType3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputType3KeyReleased
        if(evt.getKeyCode() == evt.VK_ENTER){
            beforeAdd();
        }
    }//GEN-LAST:event_inputType3KeyReleased

    private void inputType4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputType4KeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            beforeAdd();
        }
    }//GEN-LAST:event_inputType4KeyPressed

    private void buttonSaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buttonSaveKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            beforeAdd();
        }
    }//GEN-LAST:event_buttonSaveKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DelayScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DelayScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DelayScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DelayScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DelayScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonSave;
    private javax.swing.JTextArea inputReasonDelay;
    private javax.swing.JRadioButton inputType1;
    private javax.swing.JRadioButton inputType2;
    private javax.swing.JRadioButton inputType3;
    private javax.swing.JRadioButton inputType4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtReasonDelay;
    private javax.swing.JLabel txtTypeDelay;
    // End of variables declaration//GEN-END:variables
}
