/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

/**
 *
 * @author willi
 */
public class HourHistoricScreen extends javax.swing.JFrame {

    /**
     * Creates new form HourHistoricScreen
     */
    public HourHistoricScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtShotHistoric = new javax.swing.JLabel();
        imageBefore = new javax.swing.JLabel();
        imageAfter = new javax.swing.JLabel();
        inputDateFilter = new javax.swing.JFormattedTextField();
        buttonFilter = new javax.swing.JButton();
        outputEndThirdShooting = new javax.swing.JFormattedTextField();
        outputEndSecondShooting = new javax.swing.JFormattedTextField();
        txtTenthShooting = new javax.swing.JLabel();
        outputEndFourthShooting = new javax.swing.JFormattedTextField();
        txtEleventhShooting = new javax.swing.JLabel();
        outputEndFifthShooting = new javax.swing.JFormattedTextField();
        txtTwelfthShooting = new javax.swing.JLabel();
        outputEndSixthShooting = new javax.swing.JFormattedTextField();
        outputEndSeventhShooting = new javax.swing.JFormattedTextField();
        outputEndEighthShooting = new javax.swing.JFormattedTextField();
        outputEndNinthShooting = new javax.swing.JFormattedTextField();
        outputEndTenthShooting = new javax.swing.JFormattedTextField();
        outputEndFirstShooting = new javax.swing.JFormattedTextField();
        outputEndEleventhShooting = new javax.swing.JFormattedTextField();
        outputBeginningFirstShooting = new javax.swing.JFormattedTextField();
        outputBeginningSecondShooting = new javax.swing.JFormattedTextField();
        outputBeginningThirdShooting = new javax.swing.JFormattedTextField();
        outputBeginningFourthShooting = new javax.swing.JFormattedTextField();
        outputBeginningFifthShooting = new javax.swing.JFormattedTextField();
        txtFirstShooting = new javax.swing.JLabel();
        outputBeginningSeventhShooting = new javax.swing.JFormattedTextField();
        txtSecondShooting = new javax.swing.JLabel();
        outputBeginningSixthShooting = new javax.swing.JFormattedTextField();
        txtThirdShooting = new javax.swing.JLabel();
        outputBeginningEighthShooting = new javax.swing.JFormattedTextField();
        txtFourthShooting = new javax.swing.JLabel();
        outputBeginningNinthShooting = new javax.swing.JFormattedTextField();
        txtFifthShooting = new javax.swing.JLabel();
        outputBeginningTenthShooting = new javax.swing.JFormattedTextField();
        txtSixthShooting = new javax.swing.JLabel();
        outputBeginningEleventhShooting = new javax.swing.JFormattedTextField();
        txtSeventhShooting = new javax.swing.JLabel();
        outputBeginningTwenlthShooting = new javax.swing.JFormattedTextField();
        outputEndTwenlthShooting = new javax.swing.JFormattedTextField();
        txtEighthShooting = new javax.swing.JLabel();
        txtNinthShooting = new javax.swing.JLabel();
        txtBeginning = new javax.swing.JLabel();
        txtEnd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Histórico de Rodagens");

        txtShotHistoric.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtShotHistoric.setText("HISTÓRICO DE RODAGENS");

        imageBefore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LeftArrow.png"))); // NOI18N

        imageAfter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RightArrow.png"))); // NOI18N

        try {
            inputDateFilter.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        inputDateFilter.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputDateFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputDateFilterKeyPressed(evt);
            }
        });

        buttonFilter.setText("FILTRAR");
        buttonFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFilterActionPerformed(evt);
            }
        });
        buttonFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buttonFilterKeyPressed(evt);
            }
        });

        try {
            outputEndThirdShooting.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        outputEndThirdShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        try {
            outputEndSecondShooting.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        outputEndSecondShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        txtTenthShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        txtTenthShooting.setText("10º RODAGEM");

        try {
            outputEndFourthShooting.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        outputEndFourthShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        txtEleventhShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        txtEleventhShooting.setText("11º RODAGEM");

        try {
            outputEndFifthShooting.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        outputEndFifthShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        txtTwelfthShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        txtTwelfthShooting.setText("12º RODAGEM");

        try {
            outputEndSixthShooting.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        outputEndSixthShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        try {
            outputEndSeventhShooting.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        outputEndSeventhShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        try {
            outputEndEighthShooting.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        outputEndEighthShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        try {
            outputEndNinthShooting.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        outputEndNinthShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        try {
            outputEndTenthShooting.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        outputEndTenthShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        try {
            outputEndFirstShooting.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        outputEndFirstShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        try {
            outputEndEleventhShooting.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        outputEndEleventhShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        try {
            outputBeginningFirstShooting.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        outputBeginningFirstShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        try {
            outputBeginningSecondShooting.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        outputBeginningSecondShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        try {
            outputBeginningThirdShooting.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        outputBeginningThirdShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        try {
            outputBeginningFourthShooting.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        outputBeginningFourthShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        try {
            outputBeginningFifthShooting.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        outputBeginningFifthShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        txtFirstShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        txtFirstShooting.setText("1º RODAGEM");

        try {
            outputBeginningSeventhShooting.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        outputBeginningSeventhShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        txtSecondShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        txtSecondShooting.setText("2º RODAGEM");

        try {
            outputBeginningSixthShooting.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        outputBeginningSixthShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        txtThirdShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        txtThirdShooting.setText("3º RODAGEM");

        try {
            outputBeginningEighthShooting.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        outputBeginningEighthShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        txtFourthShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        txtFourthShooting.setText("4º RODAGEM");

        try {
            outputBeginningNinthShooting.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        outputBeginningNinthShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        txtFifthShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        txtFifthShooting.setText("5º RODAGEM");

        try {
            outputBeginningTenthShooting.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        outputBeginningTenthShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        txtSixthShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        txtSixthShooting.setText("6º RODAGEM");

        try {
            outputBeginningEleventhShooting.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        outputBeginningEleventhShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        txtSeventhShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        txtSeventhShooting.setText("7º RODAGEM");

        try {
            outputBeginningTwenlthShooting.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        outputBeginningTwenlthShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        try {
            outputEndTwenlthShooting.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        outputEndTwenlthShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        txtEighthShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        txtEighthShooting.setText("8º RODAGEM");

        txtNinthShooting.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        txtNinthShooting.setText("9º RODAGEM");

        txtBeginning.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        txtBeginning.setText("INÍCIO");

        txtEnd.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        txtEnd.setText("FIM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtShotHistoric)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNinthShooting)
                            .addComponent(txtTenthShooting)
                            .addComponent(txtEleventhShooting)
                            .addComponent(txtTwelfthShooting)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtSecondShooting)
                                    .addComponent(txtFirstShooting)
                                    .addComponent(txtThirdShooting)
                                    .addComponent(txtFourthShooting)
                                    .addComponent(txtFifthShooting)
                                    .addComponent(txtSixthShooting)
                                    .addComponent(txtSeventhShooting)
                                    .addComponent(txtEighthShooting))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(outputBeginningFirstShooting)
                                    .addComponent(outputBeginningSecondShooting)
                                    .addComponent(outputBeginningThirdShooting)
                                    .addComponent(outputBeginningFourthShooting)
                                    .addComponent(outputBeginningFifthShooting)
                                    .addComponent(outputBeginningSeventhShooting)
                                    .addComponent(outputBeginningSixthShooting)
                                    .addComponent(outputBeginningEighthShooting)
                                    .addComponent(outputBeginningNinthShooting)
                                    .addComponent(outputBeginningTenthShooting)
                                    .addComponent(outputBeginningEleventhShooting)
                                    .addComponent(outputBeginningTwenlthShooting))))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(outputEndFirstShooting)
                            .addComponent(outputEndSecondShooting)
                            .addComponent(outputEndThirdShooting)
                            .addComponent(outputEndFourthShooting)
                            .addComponent(outputEndFifthShooting)
                            .addComponent(outputEndSixthShooting)
                            .addComponent(outputEndSeventhShooting)
                            .addComponent(outputEndEighthShooting)
                            .addComponent(outputEndNinthShooting)
                            .addComponent(outputEndTenthShooting)
                            .addComponent(outputEndEleventhShooting)
                            .addComponent(outputEndTwenlthShooting)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imageBefore)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputDateFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imageAfter)
                        .addGap(56, 56, 56)
                        .addComponent(buttonFilter)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(txtBeginning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(182, 182, 182)
                        .addComponent(txtEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(73, 73, 73)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(txtShotHistoric)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBeginning, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEnd, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFirstShooting)
                            .addComponent(outputEndFirstShooting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(outputBeginningFirstShooting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSecondShooting)
                            .addComponent(outputBeginningSecondShooting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(outputEndSecondShooting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtThirdShooting)
                            .addComponent(outputBeginningThirdShooting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(outputEndThirdShooting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFourthShooting)
                            .addComponent(outputBeginningFourthShooting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(outputEndFourthShooting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtFifthShooting))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(outputBeginningFifthShooting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(outputEndFifthShooting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSixthShooting)
                    .addComponent(outputBeginningSixthShooting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputEndSixthShooting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSeventhShooting)
                    .addComponent(outputBeginningSeventhShooting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputEndSeventhShooting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEighthShooting)
                    .addComponent(outputBeginningEighthShooting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputEndEighthShooting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNinthShooting)
                    .addComponent(outputBeginningNinthShooting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputEndNinthShooting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenthShooting)
                    .addComponent(outputBeginningTenthShooting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputEndTenthShooting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEleventhShooting)
                    .addComponent(outputBeginningEleventhShooting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputEndEleventhShooting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTwelfthShooting)
                    .addComponent(outputBeginningTwenlthShooting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputEndTwenlthShooting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageBefore)
                    .addComponent(imageAfter)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(inputDateFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(buttonFilter)))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(572, 723));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputDateFilterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputDateFilterKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            
        }
    }//GEN-LAST:event_inputDateFilterKeyPressed

    private void buttonFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonFilterActionPerformed

    private void buttonFilterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buttonFilterKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            
        }
    }//GEN-LAST:event_buttonFilterKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HourHistoricScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HourHistoricScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HourHistoricScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HourHistoricScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HourHistoricScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFilter;
    private javax.swing.JLabel imageAfter;
    private javax.swing.JLabel imageBefore;
    private javax.swing.JFormattedTextField inputDateFilter;
    private javax.swing.JFormattedTextField outputBeginningEighthShooting;
    private javax.swing.JFormattedTextField outputBeginningEleventhShooting;
    private javax.swing.JFormattedTextField outputBeginningFifthShooting;
    private javax.swing.JFormattedTextField outputBeginningFirstShooting;
    private javax.swing.JFormattedTextField outputBeginningFourthShooting;
    private javax.swing.JFormattedTextField outputBeginningNinthShooting;
    private javax.swing.JFormattedTextField outputBeginningSecondShooting;
    private javax.swing.JFormattedTextField outputBeginningSeventhShooting;
    private javax.swing.JFormattedTextField outputBeginningSixthShooting;
    private javax.swing.JFormattedTextField outputBeginningTenthShooting;
    private javax.swing.JFormattedTextField outputBeginningThirdShooting;
    private javax.swing.JFormattedTextField outputBeginningTwenlthShooting;
    private javax.swing.JFormattedTextField outputEndEighthShooting;
    private javax.swing.JFormattedTextField outputEndEleventhShooting;
    private javax.swing.JFormattedTextField outputEndFifthShooting;
    private javax.swing.JFormattedTextField outputEndFirstShooting;
    private javax.swing.JFormattedTextField outputEndFourthShooting;
    private javax.swing.JFormattedTextField outputEndNinthShooting;
    private javax.swing.JFormattedTextField outputEndSecondShooting;
    private javax.swing.JFormattedTextField outputEndSeventhShooting;
    private javax.swing.JFormattedTextField outputEndSixthShooting;
    private javax.swing.JFormattedTextField outputEndTenthShooting;
    private javax.swing.JFormattedTextField outputEndThirdShooting;
    private javax.swing.JFormattedTextField outputEndTwenlthShooting;
    private javax.swing.JLabel txtBeginning;
    private javax.swing.JLabel txtEighthShooting;
    private javax.swing.JLabel txtEleventhShooting;
    private javax.swing.JLabel txtEnd;
    private javax.swing.JLabel txtFifthShooting;
    private javax.swing.JLabel txtFirstShooting;
    private javax.swing.JLabel txtFourthShooting;
    private javax.swing.JLabel txtNinthShooting;
    private javax.swing.JLabel txtSecondShooting;
    private javax.swing.JLabel txtSeventhShooting;
    private javax.swing.JLabel txtShotHistoric;
    private javax.swing.JLabel txtSixthShooting;
    private javax.swing.JLabel txtTenthShooting;
    private javax.swing.JLabel txtThirdShooting;
    private javax.swing.JLabel txtTwelfthShooting;
    // End of variables declaration//GEN-END:variables
}
