/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

/**
 *
 * @author willi
 */
public class OnlineStation extends javax.swing.JFrame {

    /**
     * Creates new form OnlineStation
     */
    public OnlineStation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtOnlineStation = new javax.swing.JLabel();
        allTableOnlineStation = new javax.swing.JScrollPane();
        tableOnlineStation = new javax.swing.JTable();
        buttonFilter = new javax.swing.JButton();
        inputStatusStation = new javax.swing.JComboBox<>();
        buttonDesconect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estações Online");
        getContentPane().setLayout(null);

        txtOnlineStation.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtOnlineStation.setText("ESTAÇÕES ONLINE");
        getContentPane().add(txtOnlineStation);
        txtOnlineStation.setBounds(170, 20, 240, 32);

        tableOnlineStation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nome", "Siituação"
            }
        ));
        allTableOnlineStation.setViewportView(tableOnlineStation);

        getContentPane().add(allTableOnlineStation);
        allTableOnlineStation.setBounds(17, 70, 545, 255);

        buttonFilter.setText("FILTRAR");
        buttonFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFilterActionPerformed(evt);
            }
        });
        buttonFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buttonFilterKeyPressed(evt);
            }
        });
        getContentPane().add(buttonFilter);
        buttonFilter.setBounds(190, 340, 90, 30);

        inputStatusStation.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        inputStatusStation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "ONLINE", "OFFLINE" }));
        inputStatusStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputStatusStationActionPerformed(evt);
            }
        });
        inputStatusStation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputStatusStationKeyPressed(evt);
            }
        });
        getContentPane().add(inputStatusStation);
        inputStatusStation.setBounds(20, 340, 140, 29);

        buttonDesconect.setText("DESCONECTAR");
        buttonDesconect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDesconectActionPerformed(evt);
            }
        });
        buttonDesconect.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buttonDesconectKeyPressed(evt);
            }
        });
        getContentPane().add(buttonDesconect);
        buttonDesconect.setBounds(310, 340, 120, 30);

        setSize(new java.awt.Dimension(587, 422));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFilterActionPerformed
        
    }//GEN-LAST:event_buttonFilterActionPerformed

    private void buttonFilterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buttonFilterKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){

        }
    }//GEN-LAST:event_buttonFilterKeyPressed

    private void inputStatusStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputStatusStationActionPerformed
        
    }//GEN-LAST:event_inputStatusStationActionPerformed

    private void inputStatusStationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputStatusStationKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            
        }
    }//GEN-LAST:event_inputStatusStationKeyPressed

    private void buttonDesconectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDesconectActionPerformed
        
    }//GEN-LAST:event_buttonDesconectActionPerformed

    private void buttonDesconectKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buttonDesconectKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            
        }
    }//GEN-LAST:event_buttonDesconectKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OnlineStation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OnlineStation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OnlineStation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OnlineStation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OnlineStation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane allTableOnlineStation;
    private javax.swing.JButton buttonDesconect;
    private javax.swing.JButton buttonFilter;
    private javax.swing.JFormattedTextField inputFirstDateFilter;
    private javax.swing.JComboBox<String> inputStatusStation;
    private javax.swing.JTable tableOnlineStation;
    private javax.swing.JLabel txtOnlineStation;
    // End of variables declaration//GEN-END:variables
}
